In [8]:
import pandas as pd
import numpy as np

In [7]:
pd.__version__

'2.1.1'

In [9]:
np.__version__

'1.23.1'

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10,2)
#creates a numpy array from start,end,step-size

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)
#creates a 1d of 5 0's, type float

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,5))
# shape = (number of rows, number of columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((1,6))

array([[1., 1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,10,3)
#going from 0 to 10, give me 3 numbers evenly spaced between 0 and 10
#np.linspace(start,stop,how many numbers we want)

array([ 0.,  5., 10.])

In [17]:
np.eye(5)
#creates an identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(1)
#returns a random number -with the shape in mind- of [0,1)

array([0.89753621])

In [21]:
np.random.rand(2,3)
#(number of rows, number of columns)

array([[0.60485869, 0.29810854, 0.38065076],
       [0.94583337, 0.42475806, 0.55989827]])

In [22]:
np.random.randn(5)
#np.random.randn() has a standard normal distribution
#for example you can get negative numbers too, values closer to zero have a higher chance to appear

array([-0.51873413, -0.31703392,  0.49790581, -1.29874567, -0.85585755])

In [24]:
np.random.randint(0,101,5) #from [0,101) give me 5 numbers
#these are whole integers

array([76, 92, 57, 15, 27])

In [25]:
np.random.randint(0,101,(2,2)) #same thing but with the shape of (2,2)

array([[32, 71],
       [ 0, 86]])

In [28]:
np.random.seed(101) #sets a particular set for random numbers
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [32]:
arr = np.arange(0,25)
arr.reshape(5,5) #can only reshape into valid shapes, since we need 25 numbers, a shape of (5,4)
#wont work since that can only fit 20 numbers

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr = np.random.randint(0,101,10)
ranarr.max()

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])